// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"

	"github.com/google/uuid"
)

type Log struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	CreatedAt time.Time
	Level     string
	Service   string
	Msg       string
}

type User struct {
	ID             uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
	Email          string
	HashedApiKey   string
	HashedPassword string
	Subscription   bool
}
